[package]
name = "soustitle-rs"
version = "0.1.0"
authors = ["mdauthentic <muideen.lawal320@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = "3.2.22"